categories1={"OCCASIONS & HOLIDAYS":["Decoration",
"Special Occasions",
"Party Supplies", 
"Graduation Parties",
"Birthday Supplies",
"National Day",
"Foundation Day",
"Ramadan Decorations", 
"Eid Decorations",
"Back to School",
"New Year"],
"HOUSEHOLD GEARS":[
"Kitchen Tools",
"Ceramic",
"Glassware",
"Melamine",
"Serving Plates",
"Tableware",
"Baking Tools & Accessories",
"Others",
"Aluminium"
],
"ANTIQUES & GIFTS":["Antiques & Décor",
"Candle & Scents",
"Gifts & Supplies",
"Boxes & Wrappings",
"Hangings & Wall Décor",
"Others" ],
"CLEANING PRODUCTS":[
"Cleaning Supplies",
"Cleaning Tools",
"Cleaning Liquids",
"Others"],
"PLASTICS PRODUCTS":["Kitchen Plastics",
"Cleaning Plastics", 
"Plastic Bags",
"Plastic Boxes",
"Others"],
"PAPER PRODUCTS":["Paper Wraps",
"Paper Supplies",
"Paper Rolls",
"Others"],
"ORGANIZERS & STORAGE":["Storage Products",
"Organizers Products"
],
"PERSONAL CARE":[
"Body Care",
"Hand Care",
"Hair Care",
"Face Care",
"Skin Care",
"Baby Care",
"Baby Supplies",
"Oral & Dental Care",
"Others" ],
"STATIONERY & SUPPLIES":[
"School Stationary", 
"Office Stationary", 
"Home Stationary", 
"Stationary Tools", 
"Stationary Accessories", 
"Statioanry Packages", 
"Sewing Tools",
"Others" 
],
"ACCESSORIES":[
"Personal Accessories",
"Hairbands & Headbands", 
"Jewelry & Fashion",
"Ladies Hand Bags", 
"Kids Bags", 
"Travel Bags", 
"Others" 
],
"PERFUMES & MAKEUP":[
"Perfumes & Scents", 
"Makeup Products", 
"Makeup Supplies", 
"Makeup Tools", 
"Accessories", 
"Others", 
],
"ELECTRONICS":[
"Cables & Chargers", 
"Kitchen Products", 
"Baking Machines", 
"Mobile Accessories",
"Headphones",
"Batteries", 
"Accessories",   
],
"Outdoor & Pets":[
"Travel Tools", 
"BBQ Tools & Supplies", 
"Car Accessories",
"Charcoal & Accessories",
"Pets Supplies",  
"Ropes & Wires",
"Tool Kits", 
"Others" 
],
"FOOD":[
"Canned Food",
"Chocolate & Candy",
"Light & Crunchy Foods",
"Food Packs", 
"Others" 
],
"CLOTHES":[
"Men Clothes",
"Women Clothes", 
"Girls Clothes",
"Boys Clothes",
"Baby Clothes",
"Fabrics",
"Others"    
],
"TOYS":[
"Educational Toys",
"Soft Toys",
"Boys Games",
"Girls Games",
"Sports Games",
"Others"
]}

print(list(categories1.keys()))